### ISSUE TITLE
[Design] The Design of sessions midlleware.

### ISSUE THREAD

**Issue by brotherlu-xcq** [hertz-contrib/sessions#1]
# The sketchy design of sessions midlleware.
## Session Workflow
![image](https://user-images.githubusercontent.com/25661357/181470510-b53d659e-7f41-4bb3-8957-c409654d8f3e.png)

## Session Transmit
set the session to RequestContext, users also find it in RequestContext. 
example
```go
h.Use(func(c context.Context, ctx *app.RequestContext) {
    ctx.Set("SESSION", &Session{"1144433"})
}).GET("/session", func(c context.Context, ctx *app.RequestContext) {
  if s, ok := ctx.Get("SESSION"); ok {
	session := s.(*Session)
	ctx.JSON(consts.StatusOK, common.NewSuccess(session.SessionId))
  }
})
```

## Session Expire
- every request will refresh it own lastActiveTime of session,
- a scheduled task run at backend to check the session's lastActiveTime, if session is expired, remove it. this method also put in SessionManager.

##  Session Struct
```go
type Sessioner interface {
	ID() string
	Get(key interface{}) interface{}
	Set(key interface{}, val interface{})
	Delete(key interface{})
	Clear()
	AddFlash(value interface{}, vars ...string)
	Flashes(vars ...string) []interface{}
	Options(Options)
}

type Options struct {
	Path   string
	Domain string
	MaxAge   int
	Secure   bool
	HttpOnly bool
}

type Session struct {
	ID string
	Values  map[interface{}]interface{}
	Options *Options
	IsNew   bool
	store   Store
	name    string
	lastActiveTime time.Time
}

type session struct {
	name string
	session *Session
	store *Store
}

type Store interface {
	GET(ctx *app.RequestContext, id string) (*Sessioner, error)
	New(ctx *app.RequestContext, name string) (*Sessioner, error)
	Save(ctx *app.RequestContext, s *Sessioner) error
}

type StoreOptions struct {
	timeout time.Duration
	trackModel string // cookie, url
}
```
- timeout: config the session timeout
- store: the session storage, mainly create and save session, and execute the expire session task.
- trackModel: we extract the JsessionId from cookie or url.

the Store as a extension point for user who want to save sessions in database or kv storage.

**Comment by brotherlu-xcq** [comment]
Hi, @Duslia / @GuangmingLuo . Could you help me review the design of session middleware?

**Comment by Duslia** [comment]
Maybe you can refer to these two projects: 
https://github.com/gorilla/sessions/blob/master/store.go
https://github.com/gin-contrib/sessions
It looks like it's missing some interfaces and I don't know what the `Session` struct is.

**Comment by brotherlu-xcq** [comment]
Ok, I will refer to it, and give more detail about the session later.

**Comment by brotherlu-xcq** [comment]
@Duslia The gin session use the implement of gorilla session, it always save the session data to cookie. every time it request the backend, it will create a new session which filled data form cookie. 
It is not same with other sessions implement like tomcat, and also not support the scene like browser block the cookie. so I want use the implement of tomcat. return the session id to the browser, and every request will use the session it to find the session in server.
I have update the design, could you review it?

**Comment by Duslia** [comment]
If you return the sessionid to browser, then where you save it? And how does next request use it?

**Comment by brotherlu-xcq** [comment]
When the client first time request our server, I will create a session for it and store the session id in cookie or rewrite the url to put it into url like `;sessionid=xxxx`. 
then the next request can use the sessionid in cookie or url to find the session out in our server.

**Comment by rogerogers** [comment]
https://github.com/gofiber/fiber/blob/master/middleware/session/README.md

This might help.

**Comment by Duslia** [comment]
Ok I got it. I think the first param should be the standard context, `context.Context`, since there maybe some requirements to save to redis or other sotrage. The rest of the design is fine. <img width="1170" alt="image" src="https://user-images.githubusercontent.com/37136584/182308395-eac26f18-bee0-48aa-b6d9-a555f77278ef.png">

**Comment by brotherlu-xcq** [comment]
OK，I will change it and start the coding.
