### ISSUE TITLE
redis支持集群

### ISSUE THREAD

**Issue by R2coding2run** [hertz-contrib/sessions#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FGYFFFF** [comment]
请详细描述你的问题

**Comment by R2coding2run** [comment]
是否支持redis集群，看用例是不支持的

**Comment by li-jin-gou** [comment]
@R2coding2run 目前用的 redis sdk 不支持集群模式，参考 https://github.com/gomodule/redigo/issues/386 。
如果比较急的话可以参考 session redis 的实现，替换一下 redis 的 sdk，自己实现一个。

**Comment by li-jin-gou** [comment]
@R2coding2run done
